### ISSUE TITLE
Troubleshooting solr

### ISSUE THREAD

**Issue by tomosaigon** [hashbangcode/vlad#140]
I'm running vlad-dev and have Apache solr enabled, and the "web admin" (I guess, vlad is my first experience with solr) at http://mybox.local:8081/solr is working - although when I select the vlad core and click on "ping" the icon becomes a spinner which never stops.

I'm trying to configure Drupal search_api_solr to use the solr server which by default would be http://mybox.local:8983/solr but that's not working, and neither is http://localhostl:8983/solr reachable from the box's shell, nor does there appear to be anything running/listening on port 8983 via netstat.

I don't know if this is a tomcat or getty or solr issue or what logs I should look at to see if anything's not starting as it should?

**Comment by philipnorton42** [comment]
Solr can be a pain to troubleshoot. I would start off in the error logs in the directory /var/log/tomcat6. You've found the correct admin screens so that's the other part of the troubleshooting process.

I can confirm that the 'ping' response in the control panel doesn't work. But I've not really done much about this as the two main Drupal modules (Apache Solr and Search API) are able to ping the Solr server without any trouble. If you find out what is going on there that would be great :)

**Comment by tomosaigon** [comment]
It seems that Solr isn't configured to listen on localhost:8983 (unlike some lines in existing configuration files and in many Solr tutorials online). Playing around with the admin web thingy, I could figure out where it was querying and documented it over at https://github.com/hashbangcode/vlad/wiki/Configuring-Drupal's-search_api-for-Solr

**Comment by philipnorton42** [comment]
Sorry, I didn't realise that you were looking at the wrong port. Because Solr is being served by tomcat the default port is 8080, so this is tweaked slightly so that other services (like Apache) can run correctly. Port 8983 is the default port used by Jetty, which isn't being used here.

We are currently working on a new documentation site so that should help other people in the same boat. 

One question I do have is where are the existing configuration files you found that have the wrong port? They might be worth looking into :)

**Comment by tomosaigon** [comment]
Keep in mind I was/am a complete noob to Solr. I didn't know/see how the service was configured or running so I went into /home/solr and snooped around vlad/conf/solrconfig.xml (or vlad/conf/scripts.conf) and see:
${solr.replication.masterUrl:http://localhost:8983/solr

Similarly:
vlad/conf/solrcore.properties:solr.replication.masterUrl=http://localhost:8983/solr
