### ISSUE TITLE
Notice board - ideas welcome!

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#142]
@philipnorton42 and I have discussed this before but it was never added as a public issue for discussion and to remind us to actually do it. This issue corrects that.

There is a clear need for there to be some way to notify Vlad users of any major changes to the system beyond the issue queue, the commit history and the changelog in the docs. The addition of breaking changes & new features are probably the most important reasons for this need.

The last time this was discussed we got as far as agreeing that we needed some sort of notice board to fulfil this need but the specifics still need to be nailed down. I'd like to kick this discussion off with some points/opinions:

- A Twitter account would be nice and easy though I'd be concerned about important announcements getting easily lost in the noise. Maybe a Twitter account could work if it was part of a larger solution.

- I personally would like to see something with an RSS feed, that way people would have plenty of options as to how they want to consume the info published plus it's the antithesis of Twitter in terms noise.

- Free is better than not free (free as in beer, not free as in the drummer from Mastodon).

- Anything that requires maintenance or additional regular dev time should be avoided for obvious reasons. No Drupal, Wordpress etc.

I'm gonna do some research based on those requirements. If anyone else has any opinions/suggestions/ideas please chip in via the comments.

**Comment by philipnorton42** [comment]
Been thinking about this as well recently. I think breaking changes before we get version 1.0 out are "ok" but not ideal. There were just some things that needed to be done and make sense to do before we have a larger user base. The types of breaking changes might be:

* Changes to variables, easily sorted by swapping out the correct variable or the correct variable value.
* Changes to system components, which is slightly more difficult to solve and might involve rebuilding the box.

So in terms of getting the message out there:

* Twitter :-1: Yeah, it's far too easy to never notice stuff on Twitter. I hardly look at it anymore anyway.
* RSS feeds have their uses, but I haven't used an RSS reader in about 3 years (probably since Google Reader shut down) so I don't see the point of them much unless there is something for them to be printed on, like a website or something...
* Yup.
* I don't mind putting something on hashbangcode.com. I'm just conscious of not allowing the message we are trying to convey be diluted by everything else on the site.

Other options include:
* Mailing list : no idea how to set this up, but it would get the message out.
* Google group : easy to subscribe to, and allows two way chatter and discussions. Although this would move the key discussions away from github, which is may be bad? I use it for a couple of groups and I know that Ansible also use it.
* irc : nope :)
* Maybe we could add something to the documentation? Obviously would be a pain to update the docs every time we needed to push an update, but we could use a JavaScript solution or something. I'll have a look when I have a minute.

I'll have a poke about at other doc sites/projects and see how they do their news.

**Comment by danbohea** [comment]
Following our discussion at DrupalCamp London, here is the new Vlad notice board on WordPress.com:

https://vladnotices.wordpress.com

@philipnorton42 You need to create an account at WordPress.com (if you don't already have one) for me to be able to add you as a user.

Hooray for WordPress.com! :D

**Comment by danbohea** [comment]
Oh and this is how we post code apparently:

https://en.support.wordpress.com/code/posting-source-code/

**Comment by danbohea** [comment]
Closing as this is now setup and working.

WORDPRESS.COM!!!
