### ISSUE TITLE
solr-4.7.2.tgz no longer available at http://www.mirrorservice.org

### ISSUE THREAD

**Issue by chrisrikli** [hashbangcode/vlad#232]
Only 4.10.4.tgz is available.  Linked is a patch updating /vlad/playbooks/roles/solr/tasks/debian_solr.yml accordingly.

http://pastebin.com/raw.php?i=9SLNJGPp

**Comment by danbohea** [comment]
Thanks for the patch @chrisrikli . With Vlad being on GitHub, managing / reviewing / sharing / attributing contributions is a whole load easier with [pull requests](https://help.github.com/articles/using-pull-requests/) rather than patches.

Shout if you need assistance, I remember scratching my head a fair bit the first time I had to do a pull request :)

**Comment by chrisrikli** [comment]
Sounds good @danbohea I'll do that in the future.

**Comment by danbohea** [comment]
Good stuff. Would you mind resubmitting this fix as a pull request?

**Comment by philipnorton42** [comment]
That's the annoying thing about Solr. When they update their version they commonly delete the older ones from all of their mirrors. Which means having to run around getting new versions.
Also, thanks for the patch, but as Dan said a pull request would be great and would mean that you would get attribution for the fix as well.

**Comment by chrisrikli** [comment]
Done and pull request submitted.

**Comment by philipnorton42** [comment]
Thanks for the pull request. I have now tagged version 1.1.3 which contains your patch :+1:
