### ISSUE TITLE
Add option to trigger Drupal install as part of Ansible provisioning

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#250]
I think that there is a clear need to have Drupal "pre-installed" in some use cases and adding this feature via a simple setting or two would be a great way to provide it. We're almost there already: we have installer scripts written and even automatic provisioning from make files, we just need to join the dots.

**Comment by zxaos** [comment]
It'd be great if part of this supported keeping the default index.php somewhere else - it's got some useful links and data and is lost when a Drupal install is made. I think skipping right to an installed Drupal will likely lead to some people forgetting how to get to Adminer, say.

**Comment by danbohea** [comment]
I guess it could be moved to somewhere within `/vlad_aux`. I'd never really considered hanging on to it but now that you mention it...

**Comment by philipnorton42** [comment]
What about if we did the following:
- If no index.php file is present then we create the Vlad welcome index.php.
- If an index file is already present then we create the same file, but call it vlad.php

However, I'm not sure how useful that is as it wouldn't be immediately obvious where it was. Updating the documentation with this location might work, but people don't read that stuff, do they? :stuck_out_tongue_closed_eyes: 

As for the original idea. This gets a :+1: from me. The WordPress version of this system (called VVV) allows you to install WordPress along with the box. In fact it installs several different versions of WordPress, which seems like overkill to me.

Let's keep this simple then. We could provide a setting where we could allow users to install Drupal automatically out of the box, which would simply run one of the installer scripts. Something like the following:

    vlad_drupal_install: drupal7

Possible values might be drupal6, drupal7, drupal8, drupal8dev.

This would obviously clash with the make provisioning variables so I would suggest that the drush_make_file setting should get precedence by doing and check on the Drupal install task that will skip the task if that value is anything other than "".

**Comment by danbohea** [comment]
Would vlad.php even be accessible once Drupal is installed?

**Comment by zxaos** [comment]
@danbohea How do you mean?

In the sense of "will apache server vlad.php from that vhost"? Then yes.
In the sense of "will vlad.php exist after Drupal is installed?" Then probably not unless it's added afterward - the install scripts tend to clobber anything in their way in my experience.

What about taking VVV's example and defining an ancillary vhost for vlad.php? It'd have the same set of tasks regardless of how Drupal is installed, could be consistently named between instances of Vlad (since optionally it could be independent of the box name), and wouldn't need to worry about being clobbered by any project related stuff. No matter the project structure used, it'd just be off it its own directory somewhere as a property of the VM.

Just treat it like `pimpmylog` essentially. Make `/var/www/vlad`

**Comment by danbohea** [comment]
I meant would Apache successfully serve vlad.php once it's sat beside Drupal in docroot - I honestly couldn't remember the outcome of such a situation - thanks for answering. Either way, I'd prefer not to muddy people's docroot directory with Vlad specific files forcing them to add vlad.php to their Drupal project's .gitignore file.

Having a separate directory within the VM that could be used to serve files from would be OK though :)

**Comment by danbohea** [comment]
This functionality is now in the Galaxy branch (see drupal role) but without relocating Vlad's default index.php yet.

**Comment by mvance** [comment]
I was about to open a separate issue to suggest creating an example custom playbook, but I realized that the idea could potentially tie in with this issue…

With the switch from custom roles to custom playbooks, it would be handy to have a fully functional yet simple custom playbook that users could use as the basis for customizing. I'm currently working through converting my old custom role into a custom playbook and it would be helpful to have a known working example to refer to. I'm not sure if it would make sense to have the example custom playbook live in a separate repository or within VLAD. But I thought it was worth mentioning the idea here, since it might be possible to meld the two ideas.

**Comment by danbohea** [comment]
This should be a separate issue really but while I'm here see [what's left of my custom play](https://github.com/danbohea/vlad_custom) for a super simple working example to possibly base your custom play on.

Also see (and feel free to add your thoughts to) [this issue](https://github.com/hashbangcode/vlad-role/issues/1) for how we might provide a more "official" example to work from.

**Comment by danbohea** [comment]
The core of this issue is addressed in Vlad 1.1.6 ([docs](http://vlad-docs.readthedocs.org/en/latest/usage/variables/#drupal)).

I'm gonna close this. Let's raise a new issue if we still want to discuss preserving the contents on Vlad's index.php after Drupal is installed.
