### ISSUE TITLE
ansible.cfg when using VMware/Parallels Desktop?

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#266]
Was looking through the code and noticed `ansible.cfg` contains:

`ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key`

This would be wrong for provider `vmware` or `parallels`. Is this overridden elsewhere? I grepped, but I'm not seeing anything. Would that have any actual implications or require overrides for users of the other two systems?

**Comment by philipnorton42** [comment]
Very true, this variable is not overridden anywhere so it won't work for vmware or parallels. Some extra investigation needed here I think...

**Comment by zxaos** [comment]
I'm pretty sure this isn't an issue - I've been running vlad with VMWare successfully for quite a while now.

In fact, we should probably just drop that line from ansible.cfg completely. This is because... (snip from https://github.com/mitchellh/vagrant/pull/5044/ )

> Ansible (tested with 1.9.1) behaves with following precedence rules (listed from lowest to highest priority):
>
> private_key_file defined in an Ansible configuration file (e.g. local ansible.cfg)
> ANSIBLE_PRIVATE_KEY_FILE environment variable
> --private-key command line argument
>ansible_private_key_file=... value(s) in the inventory file
>
> ...
>
> So, Good News: The additional private keys are correctly passed to the ssh command by ansible-playbook, even when ansible_ssh_private_key_file is set in the inventory.

Essentially Vagrant correctly passes keys on the command line when it invokes ansible, so we don't need to worry about where the keys are or the provider we're using.

So here's a PR to remove it altogether #320

**Comment by zxaos** [comment]
@wizonesolutions I think merging #320 resolved this issue :-)

**Comment by philipnorton42** [comment]
Cool! @wizonesolutions if you can confirm this when you get a minute we can close this issue off :)

**Comment by wizonesolutions** [comment]
I don't even remember the context for this. Close it! :)
16. des. 2015 16:36 skrev "Philip Norton" <notifications@github.com>:

**Comment by danbohea** [comment]
Closing as theoretically fixed and the opportunity to test in the original context has passed. Please re-open if a subsequent test fails.
