### ISSUE TITLE
Contributing/developing roles after galaxy merge

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/vlad#276]
How? Don't see any docs on this in the docs. Is my only resort to change the cloned and then manually sync the changes to a separate clone?

**Comment by danbohea** [comment]
Yeah, docs are a bit behind while this stuff is still in dev branch only. I intend to have docs updated to cover this new stuff before the next tagged release.

I don't fully understand your question though - would you mind rephrasing?

**Comment by wizonesolutions** [comment]
Often one sets things up a bit differently when developing, iterating, and
testing vs. just consuming/using. Does this distinction apply for Vlad
roles? I know with Vlad itself I can simply use two repos parallel.
Am 14.09.2015 12:11 schrieb "Dan Bohea" <notifications@github.com>:

**Comment by danbohea** [comment]
Right, I _think_ I follow you now...

Personally I'm just copying tested changes from Galaxy roles downloaded by Vlad into separate clones of each respective role and committing/pushing from there. This isn't ideal and I'm considering setting something up with Git submodules to be able to do everything from one codebase that uses repos within repos. The latter approach may warrant adding a dev-only setting in Vlad that prevents it from using Galaxy to download external roles (so that Git can handle this instead). The subsequent .gitmodules file would have to never be committed back upstream to Vlad though - is it possible to add .gitmodules to .gitignore?

I guess the other thing to highlight here is that any roles that have been created and shared on Galaxy aren't intended to be exclusive to Vlad, therefore developing & testing such roles doesn't _have_ to be in the context of Vlad's codebase (at least initially anyway, you'll probably want to test it with Vlad eventually).

**Comment by wizonesolutions** [comment]
Yep, that's what I meant. Thanks! I'll just go with that for now.
