### ISSUE TITLE
Define guidelines for Github contributors

### ISSUE THREAD

**Issue by christopher-hopper** [hashbangcode/vlad#342]
### Problem

When pushing a recent pull request to fix a bug (see #341 for discussion) I found out the default branch did not hold the most up-to-date development code for the project. I was then asked to resubmit my changes against a different branch called `dev`.

### Suggested Solution

Create a set of [Guidelines for project contributions](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) using the Github recognised file naming convention. This will prompt contributors when they go to create a pull request.

**Comment by christopher-hopper** [comment]
[Contribution guidelines](http://vlad-docs.readthedocs.org/en/latest/contributing/contributing/) exist in the Documentation for Vlad. They specify that pull requests should not be made against the default branch `master` but don't specify which branch exactly _should_ be used. 

If the branch named `dev` is to be the branch, then we should specify that I guess, then put that into the newly created `CONTRIBUTING.md` or `./github/CONTRIBUTING.md` file.

**Comment by christopher-hopper** [comment]
Submitted a Pull Request #343 for your consideration. This should improve the contributions and reduce wasted effort for everyone.

**Comment by zxaos** [comment]
@danbohea Would we ever take a PR against master directly if it was a hotfix for an bug? I'm just hesitant to blanked-statement say that PRs will _never_ be taken against master?

**Comment by danbohea** [comment]
@zxaos Good point but even a hotfix needs to be tested and testing should really happen before code hits the master branch, even if it's not part of a formal tagged release. I've done it in the past (not very often), but then I'm aware of the source of the patch (me) and I know how much I've tested what I've written and have made a quick decision based on how badly the code needed to be fixed in `master`.

Maybe we should have a slightly more advanced branch setup that caters for more varied scenarios?

**Comment by zxaos** [comment]
Eh, fair enough. master lags behind dev enough that many issues that occur in master are probably already fixed in dev. Let's not over-complicate things. :smiley:
