### ISSUE TITLE
Drupal 8 Beta released - tweak D8 install script?

### ISSUE THREAD

**Issue by danbohea** [hashbangcode/vlad#92]
Is it worth tweaking the site install script to grab the latest beta/RC rather than the latest dev? It's currently a little tricky to establish _which_ version of D8 you've just downloaded and now that the first beta is here, awareness of specific versions is more important.

**Comment by philipnorton42** [comment]
So after some playing about I have found the following command, which will clone the latest Drupal 8 beta release:

    git ls-remote --tags http://git.drupal.org/project/drupal.git | grep refs/tags/8\.0\.0-beta | xargs -n1 | tail -n 1 |  sed 's/refs\/tags\///' | xargs -I % git clone --branch % http://git.drupal.org/project/drupal.git /var/www/site/docroot

I couldn't get drush to download Drupal 8, so this seemed like the next most sensible step. Because we are cloning a git repo then it shouldn't be too hard to find out what the code contains?

Once Drupal 8 gets released we can just replace this with a 'drush dl drupal' and update the Drupal 7 script to grab the previous version.
